# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jun/Documents/code/cpp/LeetCode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jun/Documents/code/cpp/LeetCode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jun/Documents/code/cpp/LeetCode/CMakeFiles /home/jun/Documents/code/cpp/LeetCode/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jun/Documents/code/cpp/LeetCode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graph_test

# Build rule for target.
graph_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_test
.PHONY : graph_test

# fast build rule for target.
graph_test/fast:
	$(MAKE) -f lib/CMakeFiles/graph_test.dir/build.make lib/CMakeFiles/graph_test.dir/build
.PHONY : graph_test/fast

#=============================================================================
# Target rules for targets named tree

# Build rule for target.
tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree
.PHONY : tree

# fast build rule for target.
tree/fast:
	$(MAKE) -f lib/CMakeFiles/tree.dir/build.make lib/CMakeFiles/tree.dir/build
.PHONY : tree/fast

#=============================================================================
# Target rules for targets named graph

# Build rule for target.
graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph
.PHONY : graph

# fast build rule for target.
graph/fast:
	$(MAKE) -f lib/CMakeFiles/graph.dir/build.make lib/CMakeFiles/graph.dir/build
.PHONY : graph/fast

#=============================================================================
# Target rules for targets named p140

# Build rule for target.
p140: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p140
.PHONY : p140

# fast build rule for target.
p140/fast:
	$(MAKE) -f src/CMakeFiles/p140.dir/build.make src/CMakeFiles/p140.dir/build
.PHONY : p140/fast

#=============================================================================
# Target rules for targets named p139

# Build rule for target.
p139: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p139
.PHONY : p139

# fast build rule for target.
p139/fast:
	$(MAKE) -f src/CMakeFiles/p139.dir/build.make src/CMakeFiles/p139.dir/build
.PHONY : p139/fast

#=============================================================================
# Target rules for targets named p91

# Build rule for target.
p91: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p91
.PHONY : p91

# fast build rule for target.
p91/fast:
	$(MAKE) -f src/CMakeFiles/p91.dir/build.make src/CMakeFiles/p91.dir/build
.PHONY : p91/fast

#=============================================================================
# Target rules for targets named p51

# Build rule for target.
p51: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p51
.PHONY : p51

# fast build rule for target.
p51/fast:
	$(MAKE) -f src/CMakeFiles/p51.dir/build.make src/CMakeFiles/p51.dir/build
.PHONY : p51/fast

#=============================================================================
# Target rules for targets named p52

# Build rule for target.
p52: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p52
.PHONY : p52

# fast build rule for target.
p52/fast:
	$(MAKE) -f src/CMakeFiles/p52.dir/build.make src/CMakeFiles/p52.dir/build
.PHONY : p52/fast

#=============================================================================
# Target rules for targets named p121

# Build rule for target.
p121: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p121
.PHONY : p121

# fast build rule for target.
p121/fast:
	$(MAKE) -f src/CMakeFiles/p121.dir/build.make src/CMakeFiles/p121.dir/build
.PHONY : p121/fast

#=============================================================================
# Target rules for targets named p123

# Build rule for target.
p123: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p123
.PHONY : p123

# fast build rule for target.
p123/fast:
	$(MAKE) -f src/CMakeFiles/p123.dir/build.make src/CMakeFiles/p123.dir/build
.PHONY : p123/fast

#=============================================================================
# Target rules for targets named p62

# Build rule for target.
p62: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p62
.PHONY : p62

# fast build rule for target.
p62/fast:
	$(MAKE) -f src/CMakeFiles/p62.dir/build.make src/CMakeFiles/p62.dir/build
.PHONY : p62/fast

#=============================================================================
# Target rules for targets named p131

# Build rule for target.
p131: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p131
.PHONY : p131

# fast build rule for target.
p131/fast:
	$(MAKE) -f src/CMakeFiles/p131.dir/build.make src/CMakeFiles/p131.dir/build
.PHONY : p131/fast

#=============================================================================
# Target rules for targets named p96

# Build rule for target.
p96: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p96
.PHONY : p96

# fast build rule for target.
p96/fast:
	$(MAKE) -f src/CMakeFiles/p96.dir/build.make src/CMakeFiles/p96.dir/build
.PHONY : p96/fast

#=============================================================================
# Target rules for targets named p63

# Build rule for target.
p63: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p63
.PHONY : p63

# fast build rule for target.
p63/fast:
	$(MAKE) -f src/CMakeFiles/p63.dir/build.make src/CMakeFiles/p63.dir/build
.PHONY : p63/fast

#=============================================================================
# Target rules for targets named p74

# Build rule for target.
p74: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p74
.PHONY : p74

# fast build rule for target.
p74/fast:
	$(MAKE) -f src/CMakeFiles/p74.dir/build.make src/CMakeFiles/p74.dir/build
.PHONY : p74/fast

#=============================================================================
# Target rules for targets named p35

# Build rule for target.
p35: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p35
.PHONY : p35

# fast build rule for target.
p35/fast:
	$(MAKE) -f src/CMakeFiles/p35.dir/build.make src/CMakeFiles/p35.dir/build
.PHONY : p35/fast

#=============================================================================
# Target rules for targets named p50

# Build rule for target.
p50: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p50
.PHONY : p50

# fast build rule for target.
p50/fast:
	$(MAKE) -f src/CMakeFiles/p50.dir/build.make src/CMakeFiles/p50.dir/build
.PHONY : p50/fast

#=============================================================================
# Target rules for targets named p126

# Build rule for target.
p126: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p126
.PHONY : p126

# fast build rule for target.
p126/fast:
	$(MAKE) -f src/CMakeFiles/p126.dir/build.make src/CMakeFiles/p126.dir/build
.PHONY : p126/fast

#=============================================================================
# Target rules for targets named p113

# Build rule for target.
p113: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p113
.PHONY : p113

# fast build rule for target.
p113/fast:
	$(MAKE) -f src/CMakeFiles/p113.dir/build.make src/CMakeFiles/p113.dir/build
.PHONY : p113/fast

#=============================================================================
# Target rules for targets named p31

# Build rule for target.
p31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p31
.PHONY : p31

# fast build rule for target.
p31/fast:
	$(MAKE) -f src/CMakeFiles/p31.dir/build.make src/CMakeFiles/p31.dir/build
.PHONY : p31/fast

#=============================================================================
# Target rules for targets named p111

# Build rule for target.
p111: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p111
.PHONY : p111

# fast build rule for target.
p111/fast:
	$(MAKE) -f src/CMakeFiles/p111.dir/build.make src/CMakeFiles/p111.dir/build
.PHONY : p111/fast

#=============================================================================
# Target rules for targets named p22

# Build rule for target.
p22: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p22
.PHONY : p22

# fast build rule for target.
p22/fast:
	$(MAKE) -f src/CMakeFiles/p22.dir/build.make src/CMakeFiles/p22.dir/build
.PHONY : p22/fast

#=============================================================================
# Target rules for targets named p78

# Build rule for target.
p78: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p78
.PHONY : p78

# fast build rule for target.
p78/fast:
	$(MAKE) -f src/CMakeFiles/p78.dir/build.make src/CMakeFiles/p78.dir/build
.PHONY : p78/fast

#=============================================================================
# Target rules for targets named p105

# Build rule for target.
p105: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p105
.PHONY : p105

# fast build rule for target.
p105/fast:
	$(MAKE) -f src/CMakeFiles/p105.dir/build.make src/CMakeFiles/p105.dir/build
.PHONY : p105/fast

#=============================================================================
# Target rules for targets named p93

# Build rule for target.
p93: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p93
.PHONY : p93

# fast build rule for target.
p93/fast:
	$(MAKE) -f src/CMakeFiles/p93.dir/build.make src/CMakeFiles/p93.dir/build
.PHONY : p93/fast

#=============================================================================
# Target rules for targets named p126_2

# Build rule for target.
p126_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p126_2
.PHONY : p126_2

# fast build rule for target.
p126_2/fast:
	$(MAKE) -f src/CMakeFiles/p126_2.dir/build.make src/CMakeFiles/p126_2.dir/build
.PHONY : p126_2/fast

#=============================================================================
# Target rules for targets named p112

# Build rule for target.
p112: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p112
.PHONY : p112

# fast build rule for target.
p112/fast:
	$(MAKE) -f src/CMakeFiles/p112.dir/build.make src/CMakeFiles/p112.dir/build
.PHONY : p112/fast

#=============================================================================
# Target rules for targets named p55

# Build rule for target.
p55: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p55
.PHONY : p55

# fast build rule for target.
p55/fast:
	$(MAKE) -f src/CMakeFiles/p55.dir/build.make src/CMakeFiles/p55.dir/build
.PHONY : p55/fast

#=============================================================================
# Target rules for targets named p106

# Build rule for target.
p106: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p106
.PHONY : p106

# fast build rule for target.
p106/fast:
	$(MAKE) -f src/CMakeFiles/p106.dir/build.make src/CMakeFiles/p106.dir/build
.PHONY : p106/fast

#=============================================================================
# Target rules for targets named p37

# Build rule for target.
p37: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p37
.PHONY : p37

# fast build rule for target.
p37/fast:
	$(MAKE) -f src/CMakeFiles/p37.dir/build.make src/CMakeFiles/p37.dir/build
.PHONY : p37/fast

#=============================================================================
# Target rules for targets named p64

# Build rule for target.
p64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p64
.PHONY : p64

# fast build rule for target.
p64/fast:
	$(MAKE) -f src/CMakeFiles/p64.dir/build.make src/CMakeFiles/p64.dir/build
.PHONY : p64/fast

#=============================================================================
# Target rules for targets named p79

# Build rule for target.
p79: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p79
.PHONY : p79

# fast build rule for target.
p79/fast:
	$(MAKE) -f src/CMakeFiles/p79.dir/build.make src/CMakeFiles/p79.dir/build
.PHONY : p79/fast

#=============================================================================
# Target rules for targets named p40

# Build rule for target.
p40: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p40
.PHONY : p40

# fast build rule for target.
p40/fast:
	$(MAKE) -f src/CMakeFiles/p40.dir/build.make src/CMakeFiles/p40.dir/build
.PHONY : p40/fast

#=============================================================================
# Target rules for targets named p85

# Build rule for target.
p85: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p85
.PHONY : p85

# fast build rule for target.
p85/fast:
	$(MAKE) -f src/CMakeFiles/p85.dir/build.make src/CMakeFiles/p85.dir/build
.PHONY : p85/fast

#=============================================================================
# Target rules for targets named p69

# Build rule for target.
p69: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p69
.PHONY : p69

# fast build rule for target.
p69/fast:
	$(MAKE) -f src/CMakeFiles/p69.dir/build.make src/CMakeFiles/p69.dir/build
.PHONY : p69/fast

#=============================================================================
# Target rules for targets named p45

# Build rule for target.
p45: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p45
.PHONY : p45

# fast build rule for target.
p45/fast:
	$(MAKE) -f src/CMakeFiles/p45.dir/build.make src/CMakeFiles/p45.dir/build
.PHONY : p45/fast

#=============================================================================
# Target rules for targets named p97

# Build rule for target.
p97: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p97
.PHONY : p97

# fast build rule for target.
p97/fast:
	$(MAKE) -f src/CMakeFiles/p97.dir/build.make src/CMakeFiles/p97.dir/build
.PHONY : p97/fast

#=============================================================================
# Target rules for targets named p120

# Build rule for target.
p120: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p120
.PHONY : p120

# fast build rule for target.
p120/fast:
	$(MAKE) -f src/CMakeFiles/p120.dir/build.make src/CMakeFiles/p120.dir/build
.PHONY : p120/fast

#=============================================================================
# Target rules for targets named p53

# Build rule for target.
p53: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p53
.PHONY : p53

# fast build rule for target.
p53/fast:
	$(MAKE) -f src/CMakeFiles/p53.dir/build.make src/CMakeFiles/p53.dir/build
.PHONY : p53/fast

#=============================================================================
# Target rules for targets named p39

# Build rule for target.
p39: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p39
.PHONY : p39

# fast build rule for target.
p39/fast:
	$(MAKE) -f src/CMakeFiles/p39.dir/build.make src/CMakeFiles/p39.dir/build
.PHONY : p39/fast

#=============================================================================
# Target rules for targets named p132

# Build rule for target.
p132: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p132
.PHONY : p132

# fast build rule for target.
p132/fast:
	$(MAKE) -f src/CMakeFiles/p132.dir/build.make src/CMakeFiles/p132.dir/build
.PHONY : p132/fast

#=============================================================================
# Target rules for targets named p115

# Build rule for target.
p115: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p115
.PHONY : p115

# fast build rule for target.
p115/fast:
	$(MAKE) -f src/CMakeFiles/p115.dir/build.make src/CMakeFiles/p115.dir/build
.PHONY : p115/fast

#=============================================================================
# Target rules for targets named p72

# Build rule for target.
p72: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p72
.PHONY : p72

# fast build rule for target.
p72/fast:
	$(MAKE) -f src/CMakeFiles/p72.dir/build.make src/CMakeFiles/p72.dir/build
.PHONY : p72/fast

#=============================================================================
# Target rules for targets named p133

# Build rule for target.
p133: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p133
.PHONY : p133

# fast build rule for target.
p133/fast:
	$(MAKE) -f src/graph/CMakeFiles/p133.dir/build.make src/graph/CMakeFiles/p133.dir/build
.PHONY : p133/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... graph_test"
	@echo "... tree"
	@echo "... graph"
	@echo "... p140"
	@echo "... p139"
	@echo "... p91"
	@echo "... p51"
	@echo "... p52"
	@echo "... p121"
	@echo "... p123"
	@echo "... p62"
	@echo "... p131"
	@echo "... p96"
	@echo "... p63"
	@echo "... p74"
	@echo "... p35"
	@echo "... p50"
	@echo "... p126"
	@echo "... p113"
	@echo "... p31"
	@echo "... p111"
	@echo "... p22"
	@echo "... p78"
	@echo "... p105"
	@echo "... p93"
	@echo "... p126_2"
	@echo "... p112"
	@echo "... p55"
	@echo "... p106"
	@echo "... p37"
	@echo "... p64"
	@echo "... p79"
	@echo "... p40"
	@echo "... p85"
	@echo "... p69"
	@echo "... p45"
	@echo "... p97"
	@echo "... p120"
	@echo "... p53"
	@echo "... p39"
	@echo "... p132"
	@echo "... p115"
	@echo "... p72"
	@echo "... p133"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

